// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbqqohhuwnjpzseqinvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRicXFvaGh1d25qcHpzZXFpbnZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjI5MjQsImV4cCI6MjA3NDAzODkyNH0.lfL0PeCoz3Ho0Ig_s9NmBICIet8YRei0Tn0-0yjoj_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});